### PR TITLE
Set the DOM encoding to UTF-8 when it is not specified in a feed's xml declaration

### LINKED ISSUE #112: Fatal error when accessing a content element of type xhtml in an atom feed that doesn't have an explicit xml encoding
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.26.0

#### Summary

A fatal error when accessing an entry's content element that has type xhtml in an Atom feed that doesn't specify an encoding.

#### Current behavior

A fatal error due to encoding being null when accessing the content of an entry

```
PHP Fatal error:  Uncaught TypeError: DOMDocument::__construct(): Argument #2 ($encoding) must be of type string, null given in /home/duncan/Development/PHP/development/Composer/vendor/laminas/laminas-feed/src/Reader/Extension/Atom/Entry.php:113
Stack trace:
#0 /home/duncan/Development/PHP/development/Composer/vendor/laminas/laminas-feed/src/Reader/Extension/Atom/Entry.php(113): DOMDocument->__construct()
#1 /home/duncan/Development/PHP/development/Composer/vendor/laminas/laminas-feed/src/Reader/Entry/Atom.php(97): Laminas\Feed\Reader\Extension\Atom\Entry->getContent()
#2 /home/duncan/Development/PHP/development/zend rss/test_no_encoding.php(57): Laminas\Feed\Reader\Entry\Atom->getContent()
#3 {main}
  thrown in /home/duncan/Development/PHP/development/Composer/vendor/laminas/laminas-feed/src/Reader/Extension/Atom/Entry.php on line 113
```
This is the context of the problem in file Reader/Extension/Atom/entry.php `$this->getEncoding()` returns the DOM document's encoding, which is null. 
```
                case 'xhtml':
                    $this->getXpath()->registerNamespace('xhtml', 'http://www.w3.org/1999/xhtml');
                    $xhtml  = $this->getXpath()
                        ->query($this->getXpathPrefix() . '/atom:content/xhtml:div')
                        ->item(0);
                    $d      = new DOMDocument('1.0', $this->getEncoding());

```
There was what looks to be a fix for a similar problem a _long_ time ago https://github.com/laminas/laminas-feed/commit/6018978fcbf8a7b264ae2995037d92417bc35158 but it looks simpler to me to ensure that the encoding is set immediately after loading the XML in the Reader `importString()` method.

#### How to reproduce

Using an example document from the Atom specification at https://www.ietf.org/rfc/rfc4287.txt and removing the encoding attribute from the xml declaration.
```
<?php

require '../Composer/vendor/autoload.php';

$source = <<<'END'
<?xml version="1.0" ?>
   <feed xmlns="http://www.w3.org/2005/Atom">
     <title type="text">dive into mark</title>
     <subtitle type="html">
       A &lt;em&gt;lot&lt;/em&gt; of effort
       went into making this effortless
     </subtitle>
     <updated>2005-07-31T12:29:29Z</updated>
     <id>tag:example.org,2003:3</id>
     <link rel="alternate" type="text/html"
      hreflang="en" href="http://example.org/"/>
     <link rel="self" type="application/atom+xml"
      href="http://example.org/feed.atom"/>
     <rights>Copyright (c) 2003, Mark Pilgrim</rights>
     <generator uri="http://www.example.com/" version="1.0">
       Example Toolkit
     </generator>
     <entry>
       <title>Atom draft-07 snapshot</title>
       <link rel="alternate" type="text/html"
        href="http://example.org/2005/04/02/atom"/>
       <link rel="enclosure" type="audio/mpeg" length="1337"
        href="http://example.org/audio/ph34r_my_podcast.mp3"/>
       <id>tag:example.org,2003:3.2397</id>
       <updated>2005-07-31T12:29:29Z</updated>
       <published>2003-12-13T08:29:29-04:00</published>
       <author>
         <name>Mark Pilgrim</name>
         <uri>http://example.org/</uri>
         <email>f8dy@example.com</email>
       </author>
       <contributor>
         <name>Sam Ruby</name>
       </contributor>
       <contributor>
         <name>Joe Gregorio</name>
       </contributor>
       <content type="xhtml" xml:lang="en"
        xml:base="http://diveintomark.org/">
         <div xmlns="http://www.w3.org/1999/xhtml">
           <p><i>[Update: The Atom draft is finished.]</i></p>
         </div>
       </content>
     </entry>
   </feed>
END;
$feed = Laminas\Feed\Reader\Reader::importString($source);

foreach ($feed as $entry) {
    echo $entry->getContent(), "\n";
}

```
#### Expected behavior

The contents of the content element should be returned.

### PR DESCRIPTION
**Pull request by bramley**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | yes

### Description

A unit test to demonstrate the problem that I raised in issue #112. Output of phpunit

```
duncan@duncan-OptiPlex-990 ~/Development/GitHub/laminas-feed $ phpunit --group LaminasRATOMCONTENT
PHPUnit 9.5.10 by Sebastian Bergmann and contributors.

  Warning - The configuration file did not pass validation!
  The following problems have been detected:

  Line 16:
  - Element 'source': This element is not expected.

  Test results may not be as expected.


....E....                                                           9 / 9 (100%)

Time: 00:00.019, Memory: 36.28 MB

There was 1 error:

1) LaminasTest\Feed\Reader\Entry\AtomStandaloneEntryTest::testGetsContentFromAtom10XhtmlNamespacedNoEncoding
TypeError: DOMDocument::__construct(): Argument #2 ($encoding) must be of type string, null given

/home/duncan/Development/GitHub/laminas-feed/src/Reader/Extension/Atom/Entry.php:113
/home/duncan/Development/GitHub/laminas-feed/src/Reader/Entry/Atom.php:97
/home/duncan/Development/GitHub/laminas-feed/test/Reader/Entry/AtomStandaloneEntryTest.php:262

ERRORS!
Tests: 9, Assertions: 8, Errors: 1.
```

### CODE REVIEW

**Comment by froschdesign** [comment]
@bramley 
Would you also add a fix?
Thanks in advance! 👍🏻

**Comment by bramley** [comment]
Fix added here.

File: test/Reader/Entry/AtomStandaloneEntryTest.php [hunk 1]
```diff
@@ -249,6 +249,19 @@ public function testGetsContentFromAtom10XhtmlNamespaced(): void
...
+     * XHTML document does not have encoding
+     *
+     * @group LaminasRATOMCONTENT
+     */
+    public function testGetsContentFromAtom10XhtmlNamespacedNoEncoding(): void
+    {
+        $entry = Reader\Reader::importString(
+            file_get_contents($this->feedSamplePath . '/content/atom10_XhtmlNoEncoding.xml')
+        );
+        $this->assertEquals('<p class="x:"><em>Entry Content &amp;x:</em></p>', $entry->getContent());
```
Comment (froschdesign) [inline test/Reader/Entry/AtomStandaloneEntryTest.php:263]: Add before: `$this->assertInstanceOf(Atom::class, $entry);` then Psalm is happy.

Comment (bramley) [reply test/Reader/Entry/AtomStandaloneEntryTest.php:263]: I didn't understand why the warning appeared only for the new test. Looking at the file psalm-baseline.xml, there are what appear to be exceptions for the getContent() method. It looks like another one is needed to avoid the warning on the new test.

Comment (froschdesign) [reply test/Reader/Entry/AtomStandaloneEntryTest.php:263]: > It looks like another one is needed to avoid the warning on the new test.

Please do not do this, as the file `psalm-baseline.xml` is a nightmare that will need to be resolved in the future with the next major version.

**Review by froschdesign — APPROVED** [review]

**Comment by froschdesign** [comment]
@bramley 
Thank you for your time and this contribution! 👍
